#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023 Simon-L (based on build_distro script)

###
### Simple script to build JELOS docker container toolchains
###


if [ -n "${DOCKER_WORK_DIR}" ]
then
  DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
else
  DOCKER_WORK_DIR="$(pwd)"
fi

if [ !"${ARCH}" == true ]
then
  echo "export ARCH before building."
  exit 1
fi

. config/options ""
. projects/${PROJECT}/devices/${DEVICE}/options

echo "Building toolchain docker image for ${DISTRO} for ${DEVICE}"

if [ -n "${DEVICE_ROOT}" ]
then
  BUILD_DIR="build.${DISTRO}-${DEVICE_ROOT}.${ARCH}"
  EXTRA_BUILD_ARG="--build-arg symlink=\"${DOCKER_WORK_DIR}/build.${DISTRO}-${DEVICE}.${ARCH}/toolchain\""
else
  BUILD_DIR="build.${DISTRO}-${DEVICE}.${ARCH}"
fi
TOOLCHAIN_DIR="${BUILD_DIR}/toolchain"

if [ ! -d "${TOOLCHAIN_DIR}" ]
then
  echo "${DEVICE} toolchain hasn't been built yet. Aborting."
  exit 1
fi

TEMP_TOOLCHAIN="toolchain-${DEVICE}.${ARCH}"
if [ ! -d "${TEMP_TOOLCHAIN}" ]
then
  echo "Copying ${TOOLCHAIN_DIR} to ${TEMP_TOOLCHAIN}... Please be patient!"
  cp -r ${TOOLCHAIN_DIR} ${TEMP_TOOLCHAIN}
fi

IMAGE_NAME="justenoughlinuxos/jelos-toolchain:${DEVICE}-${ARCH}"
docker build -t ${IMAGE_NAME} \
  --build-arg source_path="${TEMP_TOOLCHAIN}" \
  --build-arg target_path="${DOCKER_WORK_DIR}/${TOOLCHAIN_DIR}" \
  ${EXTRA_BUILD_ARG} \
  -f toolchain.Dockerfile .

rm -rf ${TEMP_TOOLCHAIN}